{
 "title": "Chaufeau",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ballon2 - Sortie",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date) as time_sec,\n  resistance as value,\n  \"r2\" as metric\nFROM Ballon2\nWHERE $__timeFilter(date)\nORDER BY date ASC\n"
    }
   ]
  },
  {
   "title": "Ballon1 Entrer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date) as time_sec,\n  resistance as value,\n  \"r1\" as metric\nFROM Ballon1\nWHERE $__timeFilter(date)\nORDER BY date ASC\n"
    }
   ]
  },
  {
   "title": "Conso Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(b2.date) as time_sec,\n  b2.watt as value,\n  'Total Watt' as metric\nFROM Ballon2 as b2\nWHERE $__timeFilter(b2.date) AND b2.watt > 0  /*OR $__timeFilter(b2.date) OR $__timeFilter(b1.date)*/\nGROUP BY 1\nORDER BY $__timeGroup(b2.date,$__interval,0)\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(b1.date) as time_sec,\n  b1.watt as value,\n  'Total Watt' as metric\nFROM Ballon2 as b1\nWHERE $__timeFilter(b1.date) AND b1.watt > 0  /*OR $__timeFilter(b2.date) OR $__timeFilter(b1.date)*/\nGROUP BY 1\nORDER BY $__timeGroup(b1.date,$__interval,0)\n\n"
    }
   ]
  },
  {
   "title": "Chauf eau Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  moyenne_temperature AS \"Ballon 1 - Entrer\"\nFROM Ballon1\nWHERE\n  $__timeFilter(date) AND\n  moyenne_temperature > 0\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  moyenne_temperature AS \"Ballon 2 - Sortie\"\nFROM Ballon2\nWHERE\n  $__timeFilter(date) AND\n  moyenne_temperature > 0\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  sonde_interne AS \"Sonde Interne\"\nFROM Global_info\nWHERE\n  $__timeFilter(date) AND\n  sonde_interne > 0\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    }
   ]
  },
  {
   "title": "Conso Ballon instantanne",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  watt AS \"Ballon 2 - Sortie Watt\"\nFROM Ballon2\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  watt AS \"Ballon 1 - Entrer Watt\"\nFROM Ballon1\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)\n"
    }
   ]
  },
  {
   "title": "Rendement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  avg(rend_ballon2) AS \"Ballon 2 - Sortie rendement\"\nFROM Global_info\nWHERE\n  $__timeFilter(date) AND rend_ballon2\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  avg(rend_ballon1) AS \"Ballon 1 - Entrer rendement\"\nFROM Global_info\nWHERE\n  $__timeFilter(date) AND rend_ballon1\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    }
   ]
  },
  {
   "title": "Conso Ballon Kwh dans la journee",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date, $__interval, 0),\n  (avg(watt)*0.5/1000) AS \"Ballon1 - Entre KWH\"\nFROM Ballon1\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date, $__interval, 0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date, $__interval, 0),\n (avg(watt)*0.5/1000) AS \"Ballon2 - Sortie KWH\"\nFROM Ballon2\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date, $__interval, 0)"
    }
   ]
  },
  {
   "title": "Conso Ballon Kwh dans le mois",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date, $__interval, 0),\n (avg(watt)*(count(watt)/24)/1000)/5.1 AS \"Ballon2 - Sortie KWH\"\nFROM Ballon2\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date, $__interval, 0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date, $__interval, 0),\n  (avg(watt)*(count(watt)/25)/1000)/5.1 AS \"Ballon1 - Entre KWH\"\nFROM Ballon1\nWHERE\n  $__timeFilter(date) AND\n  watt >= 0\nGROUP BY 1\nORDER BY $__timeGroup(date, $__interval, 0)"
    }
   ]
  }
 ]
}